/*
 * This file was automatically generated by EvoSuite
 * Wed Dec 04 10:34:02 GMT 2019
 */

package com.ib.client;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.ib.client.Contract;
import com.ib.client.ContractDetails;
import com.ib.client.EWrapperMsgGenerator;
import com.ib.client.Execution;
import com.ib.client.Order;
import com.ib.client.OrderState;
import com.ib.client.UnderComp;
import java.util.Locale;
import java.util.Set;
import java.util.Vector;
import java.util.function.Consumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EWrapperMsgGenerator_ESTest extends EWrapperMsgGenerator_ESTest_scaffolding {

  /**
  //Test case number: 0
  /*Coverage entropy=0.9004024235381879
  */
  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("BAG");
      locale0.toLanguageTag();
      locale0.getUnicodeLocaleAttributes();
      Vector<String> vector0 = new Vector<String>();
      OrderState orderState0 = new OrderState((String) null, "=", "!2[Bq{q/h3gu-8NL4", "BAG", 1345, 102.0, 684, (String) null, "m,");
      orderState0.m_maxCommission = (-1795.042);
      Contract contract0 = new Contract(1345, "mLXb2o*%h<uX!", "=", "wmh)xm32X{n", 1345, (String) null, "m,", "R\"]gz", ": modelPrice = ", "_q7", vector0, "#+0 >~n{z^Se", false, ";#lD", "m,");
      Order order0 = new Order();
      UnderComp underComp0 = new UnderComp();
      contract0.m_underComp = underComp0;
      order0.m_algoStrategy = "CMLYp";
      EWrapperMsgGenerator.openOrder((-1218), contract0, order0, orderState0);
      String string0 = EWrapperMsgGenerator.tickSnapshotEnd((-1272));
      assertEquals("id=-1272 =============== end ===============", string0);
  }

  /**
  //Test case number: 1
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Vector<Integer> vector0 = new Vector<Integer>();
      Vector<Object> vector1 = new Vector<Object>();
      Vector<String> vector2 = new Vector<String>();
      Contract contract0 = new Contract(0, " volatility=", "BAG", "bidPrice", 2280, "clientId = ", (String) null, "AvgVolume", "BAG", "^<;s^/#H'S", vector2, "bidPrice", false, "clientId = ", ";#lD");
      Order order0 = new Order();
      contract0.m_comboLegsDescrip = "=";
      order0.m_outsideRth = true;
      vector2.clear();
      order0.m_orderId = (-1252);
      OrderState orderState0 = new OrderState();
      orderState0.m_status = "/-Vv";
      String string0 = EWrapperMsgGenerator.openOrder(0, contract0, order0, orderState0);
      assertNotNull(string0);
  }

  /**
  //Test case number: 2
  /*Coverage entropy=1.180066384203239
  */
  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EWrapperMsgGenerator.tickOptionComputation(0, 0, 0, 0.0, 0, 0);
      Vector<Integer> vector0 = new Vector<Integer>();
      Vector<String> vector1 = new Vector<String>();
      vector1.add("3$+{bc8Q{:$B");
      Contract contract0 = new Contract(0, "BOND", (String) null, "id=0  bidSize: vol = 0.0 delta = 0.0", 1.0, "yP!=SUyYs-", " stockRangeUpper=", "yP!=SUyYs-", "Ah2{Vn*a{|qE*x:1F", " stockRangeUpper=", vector1, "yP!=SUyYs-", true, (String) null, "n!>Z3NbWYl4|Q7f\"&Pg");
      Order order0 = new Order();
      EWrapperMsgGenerator.updateNewsBulletin(0, (-912), (String) null, (String) null);
      EWrapperMsgGenerator.tickOptionComputation(2145737726, 0, 1.7976931348623157E308, Integer.MAX_VALUE, 1715.0986143, 0.0);
      // Undeclared exception!
      try { 
        EWrapperMsgGenerator.bondContractDetails(0, (ContractDetails) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ib.client.EWrapperMsgGenerator", e);
      }
  }

  /**
  //Test case number: 3
  /*Coverage entropy=2.2584261358947213
  */
  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EWrapperMsgGenerator.tickSize(0, 0, 0);
      EWrapperMsgGenerator.fundamentalData(102, "id=0  bidSize=0");
      EWrapperMsgGenerator.orderStatus(21, (String) null, 0, 102, 102, 0, 102, 68.54037, 10, "Ah2{Vn*a{|qE*x:1F");
      EWrapperMsgGenerator.tickSize(0, 102, 0);
      EWrapperMsgGenerator.tickSnapshotEnd(0);
      System.setCurrentTimeMillis(10);
      // Undeclared exception!
      try { 
        EWrapperMsgGenerator.updatePortfolio((Contract) null, 4813, 0, 0, 10, 10, 10, ">S$wGT:I+LIf>");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ib.client.EWrapperMsgGenerator", e);
      }
  }

  /**
  //Test case number: 4
  /*Coverage entropy=0.9623351446188083
  */
  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Contract contract0 = new Contract();
      Vector<Integer> vector0 = new Vector<Integer>();
      Contract contract1 = new Contract((-899), (String) null, "oAlEg", (String) null, 0.0, (String) null, "", (String) null, (String) null, "", (Vector) null, (String) null, false, " strike=", (String) null);
      contract1.m_secId = " strike=";
      Order order0 = new Order();
      OrderState orderState0 = new OrderState((String) null, "", (String) null, (String) null, (-761.011), Integer.MAX_VALUE, 1.7976931348623157E308, (String) null, "!2[Bq{q/h3gu-8NL4");
      EWrapperMsgGenerator.openOrder(0, contract1, order0, orderState0);
      // Undeclared exception!
      try { 
        EWrapperMsgGenerator.contractDetails((-1122783759), (ContractDetails) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ib.client.EWrapperMsgGenerator", e);
      }
  }

  /**
  //Test case number: 5
  /*Coverage entropy=1.830738805564335
  */
  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.tickSize(0, 0, 0);
      assertEquals("id=0  bidSize=0", string0);
      
      String string1 = EWrapperMsgGenerator.execDetailsEnd(0);
      assertEquals("reqId = 0 =============== end ===============", string1);
      
      System.setCurrentTimeMillis(0);
      String string2 = EWrapperMsgGenerator.tickSnapshotEnd(0);
      assertEquals("id=0 =============== end ===============", string2);
      
      UnderComp underComp0 = new UnderComp();
      underComp0.m_delta = (double) 752;
      String string3 = EWrapperMsgGenerator.deltaNeutralValidation(752, underComp0);
      assertEquals("id = 752 underComp.conId =0 underComp.delta =752.0 underComp.price =0.0", string3);
  }

  /**
  //Test case number: 6
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("BAG");
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      Vector<String> vector0 = new Vector<String>(set0);
      OrderState orderState0 = new OrderState((String) null, "=", "!2[Bq{q/h3gu-8NL4", "BAG", 1345, 102.0, 684, (String) null, "m,");
      Order order0 = new Order();
      OrderState orderState1 = new OrderState("currency = ", "com.ib.client.TickType", (String) null, "oAlEg", 1.7976931348623157E308, (-2029.586840920558), 1.7976931348623157E308, (String) null, (String) null);
      // Undeclared exception!
      try { 
        EWrapperMsgGenerator.openOrder((-599), (Contract) null, order0, orderState1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ib.client.EWrapperMsgGenerator", e);
      }
  }

  /**
  //Test case number: 7
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.tickPrice((-1), (-4463), 1.7976931348623157E308, (-4463));
      assertEquals("id=-1  unknown=1.7976931348623157E308  canAutoExecute", string0);
  }

  /**
  //Test case number: 8
  /*Coverage entropy=0.8950056533107491
  */
  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.tickOptionComputation(0, 0, 0, 0.0, 0, 0);
      assertEquals("id=0  bidSize: vol = 0.0 delta = 0.0", string0);
      
      Vector<Integer> vector0 = new Vector<Integer>();
      Vector<String> vector1 = new Vector<String>();
      Contract contract0 = new Contract(0, "BOND", (String) null, "id=0  bidSize: vol = 0.0 delta = 0.0", 1.0, "yP!=SUyYs-", "n!>Z3NbWYl4|Q7f\"&Pg", "yP!=SUyYs-", "Ah2{Vn*a{|qE*x:1F", "n!>Z3NbWYl4|Q7f\"&Pg", vector1, "yP!=SUyYs-", true, (String) null, "n!>Z3NbWYl4|Q7f\"&Pg");
      Order order0 = new Order();
      OrderState orderState0 = new OrderState("contractMonth = ", "n!>Z3NbWYl4|Q7f\"&Pg", "yP!=SUyYs-", (String) null, 0, 2229.0, 0, (String) null, "Ln]\"j6G~Zia=");
      String string1 = EWrapperMsgGenerator.tickOptionComputation(0, Integer.MAX_VALUE, 1.7976931348623157E308, 1.0, 0, 3);
      assertEquals("id=0  unknown: vol = N/A delta = 1.0", string1);
      
      EWrapperMsgGenerator.tickGeneric(3059, (-309), 1.7976931348623157E308);
      String string2 = EWrapperMsgGenerator.tickGeneric(1849, 0, 0.0);
      assertEquals("id=1849  bidSize=0.0", string2);
  }

  /**
  //Test case number: 9
  /*Coverage entropy=1.6082873972465448
  */
  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Contract contract0 = new Contract();
      Vector<Integer> vector0 = new Vector<Integer>();
      Contract contract1 = new Contract((-900), "", "oAlEg", (String) null, 0.0, (String) null, "", (String) null, (String) null, "", contract0.m_comboLegs, (String) null, true, " st^rike=", (String) null);
      Order order0 = new Order();
      String string0 = EWrapperMsgGenerator.tickSize(1, 1789, 109);
      assertEquals("id=1  unknown=109", string0);
      
      EWrapperMsgGenerator.tickSnapshotEnd('n');
      contract0.m_right = "zfb-Hp01QE/Vls1";
      order0.m_whatIf = false;
      String string1 = EWrapperMsgGenerator.tickOptionComputation((-1432813312), 0, 3, 0.0, 2480.28136, 786.493393064272);
      assertEquals("id=-1432813312  bidSize: vol = 3.0 delta = 0.0", string1);
      
      String string2 = EWrapperMsgGenerator.tickGeneric((-2671), (-3161), (-1194.46));
      assertEquals("id=-2671  unknown=-1194.46", string2);
      
      String string3 = EWrapperMsgGenerator.tickSnapshotEnd(121);
      assertEquals("id=121 =============== end ===============", string3);
  }

  /**
  //Test case number: 10
  /*Coverage entropy=1.543056733112554
  */
  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.tickSize(0, 0, 0);
      assertEquals("id=0  bidSize=0", string0);
      
      String string1 = EWrapperMsgGenerator.fundamentalData(102, "id=0  bidSize=0");
      assertEquals("id  = 102 len = 15\nid=0  bidSize=0", string1);
      
      String string2 = EWrapperMsgGenerator.tickSize(0, 102, 0);
      assertEquals("id=0  unknown=0", string2);
      
      Vector<String> vector0 = new Vector<String>();
      Vector<Object> vector1 = new Vector<Object>(0);
      Contract contract0 = new Contract(102, (String) null, "id  = 102 len = 15\nid=0  bidSize=0", "2c846T'Z_\"W4Y4.51[", 0, "Ah2{Vn*a{|qE*x:1F", "U", "U", (String) null, "id=0  bidSize=0", vector1, "id=0  bidSize=0", false, "id=0  bidSize=0", "^<;s^/#H'S");
      Order order0 = new Order();
      Vector<String> vector2 = new Vector<String>();
      vector2.add("'#Qe");
      vector2.clear();
      String string3 = EWrapperMsgGenerator.tickPrice(385, 2146688025, Integer.MAX_VALUE, 0);
      assertEquals("id=385  unknown=2.147483647E9  noAutoExecute", string3);
  }

  /**
  //Test case number: 11
  /*Coverage entropy=1.5271837172395382
  */
  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      int int0 = 1673;
      int int1 = 1;
      EWrapperMsgGenerator.tickString(1673, 1, (String) null);
      Contract contract0 = new Contract();
      contract0.m_multiplier = "id=1673  bidPrice=null";
      contract0.m_secIdType = "";
      EWrapperMsgGenerator.contractMsg(contract0);
      Contract contract1 = null;
      Execution execution0 = new Execution(121, 0, "airGf", (String) null, "", "", (String) null, 0, 0.0, 121, (-371), 121, 0);
      execution0.m_execId = null;
      // Undeclared exception!
      try { 
        EWrapperMsgGenerator.execDetails(0, (Contract) null, execution0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ib.client.EWrapperMsgGenerator", e);
      }
  }

  /**
  //Test case number: 12
  /*Coverage entropy=0.4
  */
  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EWrapperMsgGenerator.currentTime((-1L));
      String string0 = EWrapperMsgGenerator.currentTime((-1L));
      assertEquals("current time = -1 (Dec 31, 1969 11:59:59 PM)", string0);
  }

  /**
  //Test case number: 13
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Vector<Object> vector0 = new Vector<Object>();
      Vector<String> vector1 = new Vector<String>();
      Contract contract0 = new Contract(0, " volatility=", "BAG", "bidPrice", 2280, "clientId = ", (String) null, "AvgVolume", "BAG", "^<;s^/#H'S", vector1, "bidPrice", false, "clientId = ", "bidPrice");
      Order order0 = new Order();
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      vector1.forEach(consumer0);
      order0.m_whatIf = true;
      vector1.clear();
      order0.m_orderId = (-1252);
      OrderState orderState0 = new OrderState();
      OrderState orderState1 = new OrderState();
      String string0 = EWrapperMsgGenerator.openOrder(Integer.MAX_VALUE, contract0, order0, orderState1);
      assertNotNull(string0);
  }

  /**
  //Test case number: 14
  /*Coverage entropy=1.543056733112554
  */
  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.execDetailsEnd(1);
      assertEquals("reqId = 1 =============== end ===============", string0);
      
      EWrapperMsgGenerator.orderStatus((-1670), "Connection Closed", 0, (-1670), 0.0, 0, (-1211), (-1670), (-1670), "n1ey35HN\"k");
      String string1 = EWrapperMsgGenerator.updateMktDepth((-1670), 612, (-1670), 1, 612, 0);
      assertEquals("updateMktDepth: -1670 612 -1670 1 612.0 0", string1);
      
      String string2 = EWrapperMsgGenerator.orderStatus(399, (String) null, (-1619), 223, 223, 2180, 612, 2180, 1909, "%M$^}cmjQVm6d*V5/ s");
      assertEquals("order status: orderId=399 clientId=1909 permId=2180 status=null filled=-1619 remaining=223 avgFillPrice=223.0 lastFillPrice=2180.0 parent Id=612 whyHeld=%M$^}cmjQVm6d*V5/ s", string2);
  }

  /**
  //Test case number: 15
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("mLXb2o*%h<uX!");
      Set<String> set0 = locale0.getUnicodeLocaleKeys();
      Vector<String> vector0 = new Vector<String>(set0);
      Locale locale1 = Locale.forLanguageTag("F%5@~6(ka~CT");
      locale1.getUnicodeLocaleAttributes();
      Vector<String> vector1 = new Vector<String>(set0);
      OrderState orderState0 = new OrderState("=", "Jz9GTI0lD[z@%x^\"85C", (String) null, "currency = ", 0.0, 0.0, (-574.83248495), ")", "closeEFP");
      Contract contract0 = new Contract((-1218), ": modelPrice = ", "4", "currency = ", 1.0, "Jz9GTI0lD[z@%x^\"85C", ")", " clientId=", "{oGp", "4", vector1, ": modelPrice = ", true, "issueDate = ", "lastOptComp");
      Order order0 = new Order();
      vector1.clear();
      String string0 = EWrapperMsgGenerator.openOrder(0, contract0, order0, orderState0);
      assertNotNull(string0);
  }

  /**
  //Test case number: 16
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ContractDetails contractDetails0 = new ContractDetails((Contract) null, "ALIASES", "com.ib.client.Contract", 0.0, "ALIASES", "n`nmEOJ`", (-1), "EWTpU-@sYQ74f1x0 sJ", "ALIASES", "EWTpU-@sYQ74f1x0 sJ", "3$+{bc8Q{:$B", "CC", (String) null, "0-4ShT<?fYO,1.UK~", "EWTpU-@sYQ74f1x0 sJ");
      contractDetails0.m_convertible = false;
      // Undeclared exception!
      try { 
        EWrapperMsgGenerator.scannerData((-1), (-1), contractDetails0, "?DFnC;vmL+", "ALIASES", (String) null, "ALIASES");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ib.client.EWrapperMsgGenerator", e);
      }
  }

  /**
  //Test case number: 17
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      EWrapperMsgGenerator.tickOptionComputation((-15), 0, 0, 0.0, (-15), (-15));
      Vector<Integer> vector0 = new Vector<Integer>();
      Vector<Object> vector1 = new Vector<Object>();
      String string0 = EWrapperMsgGenerator.FINANCIAL_ADVISOR;
      System.setCurrentTimeMillis(1151L);
  }

  /**
  //Test case number: 18
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.scannerParameters((String) null);
      assertEquals("SCANNER PARAMETERS:\nnull", string0);
  }

  /**
  //Test case number: 19
  /*Coverage entropy=1.9296217656001493
  */
  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("BAG");
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      Vector<String> vector0 = new Vector<String>(set0);
      OrderState orderState0 = new OrderState(")w", (String) null, " remaining=", "?J`o z0&352wTk", 2335.234812, 684, 684, "wmh)xm32X{n", (String) null);
      String string0 = EWrapperMsgGenerator.tickSize((-91), 1767, 2697);
      assertEquals("id=-91  unknown=2697", string0);
      
      String string1 = EWrapperMsgGenerator.scannerDataEnd(1345);
      assertEquals("id = 1345 =============== end ===============", string1);
      
      String string2 = EWrapperMsgGenerator.tickOptionComputation((-2185), 1345, (-2185), 1900, 428, 459.0);
      assertEquals("id=-2185  unknown: vol = N/A delta = N/A", string2);
      
      String string3 = EWrapperMsgGenerator.tickGeneric(1900, 2134111087, 22);
      assertEquals("id=1900  unknown=22.0", string3);
      
      String string4 = EWrapperMsgGenerator.tickSnapshotEnd(1652);
      assertEquals("id=1652 =============== end ===============", string4);
  }

  /**
  //Test case number: 20
  /*Coverage entropy=2.0547779606981393
  */
  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.tickSize(0, 0, 0);
      assertEquals("id=0  bidSize=0", string0);
      
      String string1 = EWrapperMsgGenerator.fundamentalData(102, "id=0  bidSize=0");
      assertEquals("id  = 102 len = 15\nid=0  bidSize=0", string1);
      
      String string2 = EWrapperMsgGenerator.tickSize(0, 102, 0);
      assertEquals("id=0  unknown=0", string2);
      
      EWrapperMsgGenerator.tickSnapshotEnd(0);
      String string3 = EWrapperMsgGenerator.tickOptionComputation(102, (-1218), 1.7976931348623157E308, (-160.588821), (-1230.0), 649.7);
      assertEquals("id=102  unknown: vol = N/A delta = N/A", string3);
      
      String string4 = EWrapperMsgGenerator.tickGeneric(2147483646, 0, 0);
      assertEquals("id=2147483646  bidSize=0.0", string4);
      
      String string5 = EWrapperMsgGenerator.tickSnapshotEnd(0);
      assertEquals("id=0 =============== end ===============", string5);
      
      String string6 = EWrapperMsgGenerator.updateAccountValue("BV1/:?", "^<;s^/#H'S", "id=102  unknown: vol = N/A delta = N/A", (String) null);
      assertEquals("updateAccountValue: BV1/:? ^<;s^/#H'S id=102  unknown: vol = N/A delta = N/A null", string6);
      
      String string7 = EWrapperMsgGenerator.tickGeneric(20, (-1218), 62.8);
      assertEquals("id=20  unknown=62.8", string7);
  }

  /**
  //Test case number: 21
  /*Coverage entropy=1.4471627089619605
  */
  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Contract contract0 = new Contract();
      Vector<Integer> vector0 = new Vector<Integer>();
      Contract contract1 = new Contract((-899), (String) null, "oAlEg", (String) null, 0.0, (String) null, "", (String) null, (String) null, "", (Vector) null, (String) null, false, " strike=", (String) null);
      String string0 = EWrapperMsgGenerator.scannerDataEnd((-1204));
      assertEquals("id = -1204 =============== end ===============", string0);
      
      String string1 = EWrapperMsgGenerator.tickOptionComputation((-1), 13, (-899), 0, 0.0, (-1.0));
      assertEquals("id=-1  modelOptComp: vol = N/A delta = 0.0: modelPrice = 0.0: pvDividend = N/A", string1);
      
      String string2 = EWrapperMsgGenerator.tickGeneric(2144178301, (-1204), (-699.709719));
      assertEquals("id=2144178301  unknown=-699.709719", string2);
      
      String string3 = EWrapperMsgGenerator.tickSnapshotEnd((-110));
      assertEquals("id=-110 =============== end ===============", string3);
  }

  /**
  //Test case number: 22
  /*Coverage entropy=1.8408398156653452
  */
  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Contract contract0 = new Contract();
      Vector<Integer> vector0 = new Vector<Integer>();
      Vector<Integer> vector1 = new Vector<Integer>();
      Contract contract1 = new Contract(0, "oAlEg", "nextOptionPartial = ", (String) null, 2592.127259580311, (String) null, (String) null, ")w", (String) null, "RTVolume", vector1, (String) null, false, (String) null, "callable = ");
      String string0 = EWrapperMsgGenerator.scannerDataEnd((-94));
      assertEquals("id = -94 =============== end ===============", string0);
      
      String string1 = EWrapperMsgGenerator.tickOptionComputation(1679, 0, 2592.127259580311, (-1216.5969288418), 568.93, 0.0);
      assertEquals("id=1679  bidSize: vol = 2592.127259580311 delta = N/A", string1);
      
      String string2 = EWrapperMsgGenerator.tickGeneric(0, 2145710889, (-94));
      assertEquals("id=0  unknown=-94.0", string2);
      
      String string3 = EWrapperMsgGenerator.tickSnapshotEnd((-2145097555));
      assertEquals("id=-2145097555 =============== end ===============", string3);
      
      String string4 = EWrapperMsgGenerator.managedAccounts("i[pq+(5Xe6]=aI:7oy");
      assertEquals("Connected : The list of managed accounts are : [i[pq+(5Xe6]=aI:7oy]", string4);
  }

  /**
  //Test case number: 23
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Contract contract0 = new Contract();
      contract0.m_localSymbol = null;
      Execution execution0 = new Execution();
      execution0.m_acctNumber = null;
      contract0.m_currency = "BAG";
      execution0.m_avgPrice = 0.0;
      String string0 = EWrapperMsgGenerator.accountDownloadEnd("13WeekHigh");
      assertEquals("accountDownloadEnd: 13WeekHigh", string0);
  }

  /**
  //Test case number: 24
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("BAG");
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      Vector<String> vector0 = new Vector<String>(set0);
      EWrapperMsgGenerator.tickEFP(98, 23, 684, ":#m,", 684, 98, "9 <Z9/qxa=hCAy", 3734.0, 1345);
      System.setCurrentTimeMillis(23);
  }

  /**
  //Test case number: 25
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.tickPrice(0, 0, 0, 10);
      assertEquals("id=0  bidSize=0.0  canAutoExecute", string0);
  }

  /**
  //Test case number: 26
  /*Coverage entropy=1.8408398156653452
  */
  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("BAG");
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      Vector<String> vector0 = new Vector<String>(set0);
      OrderState orderState0 = new OrderState((String) null, "=", "!2[Bq{q/h3gu-8NL4", "BAG", 1345, 102.0, 684, (String) null, "m,");
      Contract contract0 = new Contract(1345, "mLXb2o*%h<uX!", "=", "wmh)xm32X{n", 1345, (String) null, "m,", "R\"]gz", ": modelPrice = ", "_q7", vector0, "#+0 >~n{z^Se", false, ";#lD", "m,");
      Order order0 = new Order();
      order0.m_algoStrategy = "CMLYp";
      EWrapperMsgGenerator.openOrder((-1218), contract0, order0, orderState0);
      ContractDetails contractDetails0 = new ContractDetails();
      String string0 = EWrapperMsgGenerator.contractDetails(405, contractDetails0);
      assertEquals("reqId = 405 ===================================\n ---- Contract Details begin ----\nconid = 0\nsymbol = null\nsecType = null\nexpiry = null\nstrike = 0.0\nright = null\nmultiplier = null\nexchange = null\nprimaryExch = null\ncurrency = null\nlocalSymbol = null\nmarketName = null\ntradingClass = null\nminTick = 0.0\nprice magnifier = 0\norderTypes = null\nvalidExchanges = null\nunderConId = 0\nlongName = null\ncontractMonth = null\nindustry = null\ncategory = null\nsubcategory = null\ntimeZoneId = null\ntradingHours = null\nliquidHours = null\n ---- Contract Details End ----\n", string0);
      
      String string1 = EWrapperMsgGenerator.nextValidId(1345);
      assertEquals("Next Valid Order ID: 1345", string1);
  }

  /**
  //Test case number: 27
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Contract contract0 = new Contract();
      Vector<Integer> vector0 = new Vector<Integer>();
      Contract contract1 = new Contract((-899), (String) null, "oAlEg", (String) null, 0.0, (String) null, "", (String) null, (String) null, "", (Vector) null, (String) null, false, " strike=", (String) null);
      Contract contract2 = new Contract();
      Order order0 = new Order();
      order0.m_ocaType = (-899);
      Vector<String> vector1 = new Vector<String>();
      vector1.clear();
      String string0 = EWrapperMsgGenerator.realtimeBar(Integer.MAX_VALUE, 1, (-154.0), 0.0, (-499.573628902), 1.7976931348623157E308, 0L, 1.7976931348623157E308, (-1794201582));
      assertEquals("id=2147483647 time = 1 open=-154.0 high=0.0 low=-499.573628902 close=1.7976931348623157E308 volume=0 count=-1794201582 WAP=1.7976931348623157E308", string0);
  }

  /**
  //Test case number: 28
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.realtimeBar(1123, 1123, 1123, 1123, 1345.0, 431.877059700918, 0L, 1123, 615);
      assertEquals("id=1123 time = 1123 open=1123.0 high=1123.0 low=1345.0 close=431.877059700918 volume=0 count=615 WAP=1123.0", string0);
  }

  /**
  //Test case number: 29
  /*Coverage entropy=1.0931471805599453
  */
  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("mLXb2o*%h<uX!");
      Set<String> set0 = locale0.getUnicodeLocaleKeys();
      Vector<String> vector0 = new Vector<String>(set0);
      OrderState orderState0 = new OrderState("pr i1GA", "mLXb2o*%h<uX!", "%foAa|fjExI\"!S}f`,", "=", 0.0, 0, 102.0, "id  = ", "pr i1GA");
      orderState0.m_initMargin = "id=0  bidSize: vol = 0.0 delta = 0.0";
      String string0 = EWrapperMsgGenerator.tickSize(0, 1900, 22);
      assertEquals("id=0  unknown=22", string0);
      
      vector0.clear();
      OrderState orderState1 = new OrderState();
      orderState1.m_maxCommission = (double) 22;
      orderState1.m_initMargin = "id  = ";
      Contract contract0 = new Contract((-1960), "id  = ", "OpenInterest", (String) null, 428, "j;o\"}`[o_wH|$W*LH", "$c@2W|?hf", "=", (String) null, (String) null, vector0, "id  = ", true, "pr i1GA", "pr i1GA");
      String string1 = EWrapperMsgGenerator.updateMktDepth((-1960), (-1960), (-1960), (-326), 2853.0, (-1252));
      assertEquals("updateMktDepth: -1960 -1960 -1960 -326 2853.0 -1252", string1);
  }

  /**
  //Test case number: 30
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.updateMktDepth(2174, 1653, 1653, 13, 160.588821, 13);
      assertEquals("updateMktDepth: 2174 1653 1653 13 160.588821 13", string0);
  }

  /**
  //Test case number: 31
  /*Coverage entropy=1.3120076729259056
  */
  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("mLXb2o*%h<uX!");
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      Vector<String> vector0 = new Vector<String>(set0);
      Order order0 = new Order();
      OrderState orderState0 = new OrderState((String) null, (String) null, "", "PROFILES", 1608.047, (-4048.303), (-2438.9973837), "PROFILES", (String) null);
      order0.m_firmQuoteOnly = false;
      String string0 = EWrapperMsgGenerator.tickOptionComputation((-619), 0, Integer.MAX_VALUE, 0, 1.7976931348623157E308, 3968.58300673);
      assertEquals("id=-619  bidSize: vol = 2.147483647E9 delta = 0.0", string0);
      
      EWrapperMsgGenerator.tickGeneric(0, 717, 20.77172);
      String string1 = EWrapperMsgGenerator.tickGeneric(36, (-386), Integer.MAX_VALUE);
      assertEquals("id=36  unknown=2.147483647E9", string1);
      
      String string2 = EWrapperMsgGenerator.updateMktDepthL2(Integer.MAX_VALUE, 1488, (String) null, 0, 1, (-1625.1693113339045), 1);
      assertEquals("updateMktDepth: 2147483647 1488 null 0 1 -1625.1693113339045 1", string2);
  }

  /**
  //Test case number: 32
  /*Coverage entropy=2.042632211710285
  */
  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Contract contract0 = new Contract();
      contract0.m_localSymbol = null;
      Execution execution0 = new Execution();
      contract0.m_comboLegsDescrip = null;
      execution0.m_acctNumber = null;
      execution0.m_avgPrice = 0.0;
      contract0.m_primaryExch = null;
      contract0.m_includeExpired = true;
      execution0.m_side = null;
      contract0.m_strike = (double) 0;
      String string0 = EWrapperMsgGenerator.execDetails(0, contract0, execution0);
      assertEquals(" ---- Execution Details begin ----\nreqId = 0\norderId = 0\nclientId = 0\nsymbol = null\nsecType = null\nexpiry = null\nstrike = 0.0\nright = null\ncontractExchange = null\ncurrency = null\nlocalSymbol = null\nexecId = null\ntime = null\nacctNumber = null\nexecutionExchange = null\nside = null\nshares = 0\nprice = 0.0\npermId = 0\nliquidation = 0\ncumQty = 0\navgPrice = 0.0\n ---- Execution Details end ----\n", string0);
      
      contract0.m_expiry = ":xsEUna2H#Eum6]Js";
      String string1 = EWrapperMsgGenerator.tickOptionComputation(0, 0, 0.0, 4392.78506529666, 852.451031544, (-3371.0));
      assertEquals("id=0  bidSize: vol = 0.0 delta = N/A", string1);
      
      String string2 = EWrapperMsgGenerator.updatePortfolio(contract0, 0, 0.0, 0, (-3371.0), 2676.9687712, 0, "]vR^8A-K%A'X0vl");
      assertEquals("updatePortfolio: conid = 0\nsymbol = null\nsecType = null\nexpiry = :xsEUna2H#Eum6]Js\nstrike = 0.0\nright = null\nmultiplier = null\nexchange = null\nprimaryExch = null\ncurrency = null\nlocalSymbol = null\n0 0.0 0.0 -3371.0 2676.9687712 0.0 ]vR^8A-K%A'X0vl", string2);
      
      String string3 = EWrapperMsgGenerator.orderStatus(0, (String) null, 2517, (-2162), (-352.2950106), 0, 0, 0.0, 0, (String) null);
      assertEquals("order status: orderId=0 clientId=0 permId=0 status=null filled=2517 remaining=-2162 avgFillPrice=-352.2950106 lastFillPrice=0.0 parent Id=0 whyHeld=null", string3);
      
      String string4 = EWrapperMsgGenerator.updateMktDepthL2(2517, 0, (String) null, (-294), (-2063), 1.7976931348623157E308, 0);
      assertEquals("updateMktDepth: 2517 0 null -294 -2063 1.7976931348623157E308 0", string4);
  }

  /**
  //Test case number: 33
  /*Coverage entropy=1.830738805564335
  */
  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.scannerDataEnd(0);
      assertEquals("id = 0 =============== end ===============", string0);
      
      String string1 = EWrapperMsgGenerator.realtimeBar(0, 0, 0, 0, (-2380.462282301), (-3635.209), 1L, (-2380.462282301), 1);
      assertEquals("id=0 time = 0 open=0.0 high=0.0 low=-2380.462282301 close=-3635.209 volume=1 count=1 WAP=-2380.462282301", string1);
      
      String string2 = EWrapperMsgGenerator.updateMktDepth(0, 0, 0, (-673), 1L, 0);
      assertEquals("updateMktDepth: 0 0 0 -673 1.0 0", string2);
      
      String string3 = EWrapperMsgGenerator.updateMktDepthL2(719, 3079, " ---- Contract Details begin ----\n", 13, 13, 1, 0);
      assertEquals("updateMktDepth: 719 3079  ---- Contract Details begin ----\n 13 13 1.0 0", string3);
  }

  /**
  //Test case number: 34
  /*Coverage entropy=1.0931471805599453
  */
  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.tickSnapshotEnd(0);
      assertEquals("id=0 =============== end ===============", string0);
      
      Contract contract0 = new Contract();
      Execution execution0 = new Execution(2071, (-1), (String) null, (String) null, (String) null, (String) null, (String) null, 1318, (-3270.9042746), (-2534), 1676, 0, 1318);
      String string1 = EWrapperMsgGenerator.execDetails((-17), contract0, execution0);
      assertEquals(" ---- Execution Details begin ----\nreqId = -17\norderId = 2071\nclientId = -1\nsymbol = null\nsecType = null\nexpiry = null\nstrike = 0.0\nright = null\ncontractExchange = null\ncurrency = null\nlocalSymbol = null\nexecId = null\ntime = null\nacctNumber = null\nexecutionExchange = null\nside = null\nshares = 1318\nprice = -3270.9042746\npermId = -2534\nliquidation = 1676\ncumQty = 0\navgPrice = 1318.0\n ---- Execution Details end ----\n", string1);
  }

  /**
  //Test case number: 35
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.realtimeBar(1123, 0L, 1123, 0L, 2260.3068, 1123, 1000L, 0L, 144);
      assertEquals("id=1123 time = 0 open=1123.0 high=0.0 low=2260.3068 close=1123.0 volume=1000 count=144 WAP=0.0", string0);
  }

  /**
  //Test case number: 36
  /*Coverage entropy=2.051681985465941
  */
  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      EWrapperMsgGenerator.tickSize(0, 0, 0);
      EWrapperMsgGenerator.fundamentalData(102, "id=0  bidSize=0");
      EWrapperMsgGenerator.orderStatus(21, (String) null, 0, 102, 102, 0, 102, 68.54037, 10, "Ah2{Vn*a{|qE*x:1F");
      EWrapperMsgGenerator.tickSize(0, 102, 0);
      EWrapperMsgGenerator.tickSnapshotEnd(0);
      EWrapperMsgGenerator.tickOptionComputation(102, (-1218), 1.7976931348623157E308, 21, (-1230.0), 649.7);
      EWrapperMsgGenerator.tickGeneric(2147483646, 0, 0);
      // Undeclared exception!
      try { 
        EWrapperMsgGenerator.fundamentalData(0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ib.client.EWrapperMsgGenerator", e);
      }
  }

  /**
  //Test case number: 37
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("BAG");
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      Vector<String> vector0 = new Vector<String>(set0);
      Contract contract0 = new Contract(684, (String) null, (String) null, "m,", 684, "m,", "BAG", "wmh)xm32X{n", (String) null, "mLXb2o*%h<uX!", vector0, "BAG", true, "", "wmh)xm32X{n");
      UnderComp underComp0 = contract0.m_underComp;
      // Undeclared exception!
      try { 
        EWrapperMsgGenerator.deltaNeutralValidation(1345, (UnderComp) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ib.client.EWrapperMsgGenerator", e);
      }
  }

  /**
  //Test case number: 38
  /*Coverage entropy=0.9623351446188083
  */
  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Vector<Integer> vector0 = new Vector<Integer>();
      Vector<String> vector1 = new Vector<String>();
      Contract contract0 = new Contract(13, "n!>Z3NbWYl4|Q7f\"&Pg", "Ah2{Vn*a{|qE*x:1F", "n!>Z3NbWYl4|Q7f\"&Pg", 1499.2826942538043, "", "~{'fU{B*/$<4mLxGM", "", "", "FF`.]V", vector1, "", true, "obTU", "");
      Order order0 = new Order();
      OrderState orderState0 = new OrderState("BOND", (String) null, (String) null, "?eO(Mn,YuMvf", 0, (-889.14437228996), 1.7976931348623157E308, "", "O");
      Order order1 = new Order();
      EWrapperMsgGenerator.openOrder(0, contract0, order1, orderState0);
      String string0 = EWrapperMsgGenerator.nextValidId(2);
      assertEquals("Next Valid Order ID: 2", string0);
  }

  /**
  //Test case number: 39
  /*Coverage entropy=2.879376754279852
  */
  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.fundamentalData((-1893), "w");
      assertEquals("id  = -1893 len = 1\nw", string0);
      
      String string1 = EWrapperMsgGenerator.realtimeBar(31, 0L, (-1.0), (-1.0), 31, 684.0, 0L, (-1.0), (-1893));
      assertEquals("id=31 time = 0 open=-1.0 high=-1.0 low=31.0 close=684.0 volume=0 count=-1893 WAP=-1.0", string1);
      
      String string2 = EWrapperMsgGenerator.nextValidId((-1122783759));
      assertEquals("Next Valid Order ID: -1122783759", string2);
      
      String string3 = EWrapperMsgGenerator.tickSize((-4856), (-4856), (-1893));
      assertEquals("id=-4856  unknown=-1893", string3);
      
      EWrapperMsgGenerator.tickGeneric((-4856), (-1122783759), (-1461.86));
      String string4 = EWrapperMsgGenerator.contractDetailsEnd((-1122783759));
      assertEquals("reqId = -1122783759 =============== end ===============", string4);
      
      String string5 = EWrapperMsgGenerator.tickSnapshotEnd(422);
      assertEquals("id=422 =============== end ===============", string5);
      
      System.setCurrentTimeMillis((-1893));
      String string6 = EWrapperMsgGenerator.historicalData((-1122783759), "highEFP", 31, (-1461.86), (-1122783759), (-1218.0), (-2630), 2517, (-2004.0655025432382), true);
      assertEquals("id=-1122783759 date = highEFP open=31.0 high=-1461.86 low=-1.122783759E9 close=-1218.0 volume=-2630 count=2517 WAP=-2004.0655025432382 hasGaps=true", string6);
      
      String string7 = EWrapperMsgGenerator.updateAccountTime("id=0  bidSize: vol = 0.0 delta = 0.0");
      assertEquals("updateAccountTime: id=0  bidSize: vol = 0.0 delta = 0.0", string7);
      
      String string8 = EWrapperMsgGenerator.receiveFA(422, (String) null);
      assertEquals("FA: null null", string8);
      
      EWrapperMsgGenerator.tickGeneric((-1122783759), 99, 1898.7740851798933);
      String string9 = EWrapperMsgGenerator.openOrderEnd();
      assertEquals(" =============== end ===============", string9);
      
      String string10 = EWrapperMsgGenerator.tickGeneric(99, (-794), (-1.0));
      assertEquals("id=99  unknown=-1.0", string10);
  }

  /**
  //Test case number: 40
  /*Coverage entropy=1.7646308653001805
  */
  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.tickOptionComputation(0, 0, 0, 0.0, 0, 0);
      assertEquals("id=0  bidSize: vol = 0.0 delta = 0.0", string0);
      
      String string1 = EWrapperMsgGenerator.orderStatus(13, "4pm BTm gX6<\"V}[U", 10, 1017, (-328.168276923), (-2145721971), 0, 1032.216, 1017, (String) null);
      assertEquals("order status: orderId=13 clientId=1017 permId=-2145721971 status=4pm BTm gX6<\"V}[U filled=10 remaining=1017 avgFillPrice=-328.168276923 lastFillPrice=1032.216 parent Id=0 whyHeld=null", string1);
      
      String string2 = EWrapperMsgGenerator.tickSize(10, (-735), 0);
      assertEquals("id=10  unknown=0", string2);
      
      String string3 = EWrapperMsgGenerator.tickSnapshotEnd(10);
      assertEquals("id=10 =============== end ===============", string3);
      
      String string4 = EWrapperMsgGenerator.tickOptionComputation(10, 3261, 10, 179.243, (-1.0), (-339.474668));
      assertEquals("id=10  unknown: vol = 10.0 delta = N/A", string4);
      
      String string5 = EWrapperMsgGenerator.tickGeneric((-2865), 2241, 1.7976931348623157E308);
      assertEquals("id=-2865  unknown=1.7976931348623157E308", string5);
  }

  /**
  //Test case number: 41
  /*Coverage entropy=2.4164983843494308
  */
  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      EWrapperMsgGenerator.fundamentalData(0, "7}]cd;");
      String string0 = EWrapperMsgGenerator.fundamentalData(0, "id  = 0 len = 6\n7}]cd;");
      assertEquals("id  = 0 len = 22\nid  = 0 len = 6\n7}]cd;", string0);
      
      String string1 = EWrapperMsgGenerator.tickEFP(2847, 2847, 0.0, "", 1435.365, 2847, "$u{6w(N\"F?XJ!scIgX", 0.0, 0);
      assertEquals("id=2847  unknown: basisPoints = 0.0/ impliedFuture = 1435.365 holdDays = 2847 futureExpiry = $u{6w(N\"F?XJ!scIgX dividendImpact = 0.0 dividends to expiry = 0.0", string1);
      
      String string2 = EWrapperMsgGenerator.updateNewsBulletin(1291, (-166), "$u{6w(N\"F?XJ!scIgX", "7}]cd;");
      assertEquals("MsgId=1291 :: MsgType=-166 :: Origin=7}]cd; :: Message=$u{6w(N\"F?XJ!scIgX", string2);
      
      String string3 = EWrapperMsgGenerator.scannerDataEnd((-166));
      assertEquals("id = -166 =============== end ===============", string3);
      
      String string4 = EWrapperMsgGenerator.openOrderEnd();
      assertEquals(" =============== end ===============", string4);
      
      EWrapperMsgGenerator eWrapperMsgGenerator0 = new EWrapperMsgGenerator();
      String string5 = EWrapperMsgGenerator.nextValidId(474);
      assertEquals("Next Valid Order ID: 474", string5);
  }

  /**
  //Test case number: 42
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("BAG");
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      Vector<String> vector0 = new Vector<String>(set0);
      OrderState orderState0 = new OrderState((String) null, "BAG", "!2[Bq{q/h3gu-8NL4", "BAG", 1345, 102.0, 684, (String) null, ":#m,");
      Order order0 = new Order();
      order0.m_referencePriceType = 0;
      orderState0.m_minCommission = (double) 0;
      vector0.clear();
      order0.m_algoStrategy = "CMLYk";
      Contract contract0 = new Contract();
      ContractDetails contractDetails0 = new ContractDetails(contract0, (String) null, "o", 1.7976931348623157E308, "open", (String) null, 35, "knD_b", (String) null, " secType=", (String) null, " avgFillPrice=", (String) null, (String) null, (String) null);
      String string0 = EWrapperMsgGenerator.scannerData(0, 0, contractDetails0, "b:J8z2Jp)`j-v]#kSCi", "7rpsobP*6", (String) null, "/-Vv");
      assertEquals("id = 0 rank=0 symbol=null secType=null expiry=null strike=0.0 right=null exchange=null currency=null localSymbol=null marketName=null tradingClass=o distance=b:J8z2Jp)`j-v]#kSCi benchmark=7rpsobP*6 projection=null legsStr=/-Vv", string0);
  }

  /**
  //Test case number: 43
  /*Coverage entropy=0.3333333333333333
  */
  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Locale locale0 = Locale.forLanguageTag("BAG");
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      Vector<String> vector0 = new Vector<String>(set0);
      Vector<Integer> vector1 = new Vector<Integer>();
      Vector<Object> vector2 = new Vector<Object>();
      String string0 = EWrapperMsgGenerator.FINANCIAL_ADVISOR;
      System.setCurrentTimeMillis(1148L);
      // Undeclared exception!
      try { 
        EWrapperMsgGenerator.contractMsg((Contract) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.ib.client.EWrapperMsgGenerator", e);
      }
  }

  /**
  //Test case number: 44
  /*Coverage entropy=2.675485446901437
  */
  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      ContractDetails contractDetails0 = new ContractDetails();
      contractDetails0.m_callable = false;
      String string0 = EWrapperMsgGenerator.bondContractDetails(78, contractDetails0);
      assertEquals("reqId = 78 ===================================\n ---- Bond Contract Details begin ----\nsymbol = null\nsecType = null\ncusip = null\ncoupon = 0.0\nmaturity = null\nissueDate = null\nratings = null\nbondType = null\ncouponType = null\nconvertible = false\ncallable = false\nputable = false\ndescAppend = null\nexchange = null\ncurrency = null\nmarketName = null\ntradingClass = null\nconid = 0\nminTick = 0.0\norderTypes = null\nvalidExchanges = null\nnextOptionDate = null\nnextOptionType = null\nnextOptionPartial = false\nnotes = null\nlongName = null\n ---- Bond Contract Details End ----\n", string0);
      
      contractDetails0.m_industry = "";
      contractDetails0.m_longName = "reqId = 78 ===================================\n ---- Bond Contract Details begin ----\nsymbol = null\nsecType = null\ncusip = null\ncoupon = 0.0\nmaturity = null\nissueDate = null\nratings = null\nbondType = null\ncouponType = null\nconvertible = false\ncallable = false\nputable = false\ndescAppend = null\nexchange = null\ncurrency = null\nmarketName = null\ntradingClass = null\nconid = 0\nminTick = 0.0\norderTypes = null\nvalidExchanges = null\nnextOptionDate = null\nnextOptionType = null\nnextOptionPartial = false\nnotes = null\nlongName = null\n ---- Bond Contract Details End ----\n";
      ContractDetails contractDetails1 = new ContractDetails(contractDetails0.m_summary, (String) null, (String) null, (-1162.4538198599), "com.ib.client.Order", "", (-2528), (String) null, "com.ib.client.Order", " notHeld=", "reqId = 78 ===================================\n ---- Bond Contract Details begin ----\nsymbol = null\nsecType = null\ncusip = null\ncoupon = 0.0\nmaturity = null\nissueDate = null\nratings = null\nbondType = null\ncouponType = null\nconvertible = false\ncallable = false\nputable = false\ndescAppend = null\nexchange = null\ncurrency = null\nmarketName = null\ntradingClass = null\nconid = 0\nminTick = 0.0\norderTypes = null\nvalidExchanges = null\nnextOptionDate = null\nnextOptionType = null\nnextOptionPartial = false\nnotes = null\nlongName = null\n ---- Bond Contract Details End ----\n", (String) null, (String) null, "couponType = ", "com.ib.client.Order");
      String string1 = EWrapperMsgGenerator.scannerData(0, 78, contractDetails1, "couponType = ", (String) null, (String) null, (String) null);
      assertEquals("id = 0 rank=78 symbol=null secType=null expiry=null strike=0.0 right=null exchange=null currency=null localSymbol=null marketName=null tradingClass=null distance=couponType =  benchmark=null projection=null legsStr=null", string1);
      
      contractDetails0.m_nextOptionDate = "#*/):iapVA";
      String string2 = EWrapperMsgGenerator.receiveFA(0, "");
      assertEquals("FA: null ", string2);
      
      EWrapperMsgGenerator.execDetailsEnd((-1799));
      String string3 = EWrapperMsgGenerator.execDetailsEnd(673);
      String string4 = EWrapperMsgGenerator.contractDetailsEnd(673);
      assertTrue(string4.equals((Object)string3));
      
      EWrapperMsgGenerator.bondContractDetails((-197), contractDetails0);
      String string5 = EWrapperMsgGenerator.tickSnapshotEnd((-2528));
      assertEquals("id=-2528 =============== end ===============", string5);
      
      String string6 = EWrapperMsgGenerator.tickString((-1799), 673, "");
      assertEquals("id=-1799  unknown=", string6);
      
      String string7 = EWrapperMsgGenerator.updatePortfolio(contractDetails0.m_summary, 0, 213.4372362014661, 0.0, 0, 0.0, (-2528), " notHeld=");
      assertEquals("updatePortfolio: conid = 0\nsymbol = null\nsecType = null\nexpiry = null\nstrike = 0.0\nright = null\nmultiplier = null\nexchange = null\nprimaryExch = null\ncurrency = null\nlocalSymbol = null\n0 213.4372362014661 0.0 0.0 0.0 -2528.0  notHeld=", string7);
  }

  /**
  //Test case number: 45
  /*Coverage entropy=1.0931471805599453
  */
  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      String string0 = EWrapperMsgGenerator.tickEFP(1653, 2174, 1653, "~QiFuKQ^k", 2174, 13, "closeEFP", 2174, 160.588821);
      assertEquals("id=1653  unknown: basisPoints = 1653.0/~QiFuKQ^k impliedFuture = 2174.0 holdDays = 13 futureExpiry = closeEFP dividendImpact = 2174.0 dividends to expiry = 160.588821", string0);
      
      System.setCurrentTimeMillis(0L);
      String string1 = EWrapperMsgGenerator.tickString((-270), (-1079), "id=1653  unknown: basisPoints = 1653.0/~QiFuKQ^k impliedFuture = 2174.0 holdDays = 13 futureExpiry = closeEFP dividendImpact = 2174.0 dividends to expiry = 160.588821");
      assertEquals("id=-270  unknown=id=1653  unknown: basisPoints = 1653.0/~QiFuKQ^k impliedFuture = 2174.0 holdDays = 13 futureExpiry = closeEFP dividendImpact = 2174.0 dividends to expiry = 160.588821", string1);
  }
}
