/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 15 03:02:37 GMT 2019
 */

package com.browsersoft.openhre.hl7.impl.regular;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.browsersoft.openhre.hl7.api.config.HL7MessageGroupItem;
import com.browsersoft.openhre.hl7.api.config.HL7Segment;
import com.browsersoft.openhre.hl7.api.regular.ExpressionElementMapper;
import com.browsersoft.openhre.hl7.api.regular.ExpressionElementMapperItem;
import com.browsersoft.openhre.hl7.impl.config.HL7MessageGroupImpl;
import com.browsersoft.openhre.hl7.impl.config.HL7MessageSegmentImpl;
import com.browsersoft.openhre.hl7.impl.config.HL7SegmentMapImpl;
import com.browsersoft.openhre.hl7.impl.regular.ExpressionElementMapperImpl;
import com.browsersoft.openhre.hl7.impl.regular.ExpressionElementMapperItemImpl;
import com.browsersoft.openhre.hl7.impl.regular.ExpressionImpl;
import com.browsersoft.openhre.hl7.impl.regular.ExpressionMatrixImpl;
import com.browsersoft.openhre.hl7.impl.regular.MessageTracerImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ExpressionMatrixImpl_ESTest extends ExpressionMatrixImpl_ESTest_scaffolding {

  /**
  //Test case number: 0
  /*Coverage entropy=2.1381822581891523
  */
  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.getValue(2, 3437);
      expressionMatrixImpl0.setValue(2, 2, (-2126));
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.addNewNode();
      MessageTracerImpl messageTracerImpl1 = new MessageTracerImpl();
      expressionMatrixImpl0.addNewNode();
      assertEquals(364, expressionMatrixImpl0.getNumberOfElements());
  }

  /**
  //Test case number: 1
  /*Coverage entropy=2.1741991176955304
  */
  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.creatMatrix(90);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.getNumberOfNodes();
      expressionMatrixImpl0.setValue(0, 1, 0);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getValue(0, 1);
      expressionMatrixImpl0.getNumberOfNodes();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      assertEquals(90, expressionMatrixImpl0.getNumberOfElements());
  }

  /**
  //Test case number: 2
  /*Coverage entropy=2.0724271546510193
  */
  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      ExpressionElementMapperImpl expressionElementMapperImpl0 = new ExpressionElementMapperImpl();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.creatMatrix(101);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getValue(364, 101);
      expressionMatrixImpl0.setValue(0, 1, 0);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.toString();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      ExpressionElementMapperImpl expressionElementMapperImpl1 = new ExpressionElementMapperImpl();
      // Undeclared exception!
      try { 
        expressionMatrixImpl0.outNoStandardConnections(false, expressionElementMapperImpl0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  /**
  //Test case number: 3
  /*Coverage entropy=2.067878052793314
  */
  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.getValue(364, 364);
      expressionMatrixImpl0.setValue(0, 1, 31);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.toString();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      assertEquals(364, expressionMatrixImpl0.getNumberOfElements());
  }

  /**
  //Test case number: 4
  /*Coverage entropy=2.0777379171354378
  */
  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      ExpressionElementMapperImpl expressionElementMapperImpl0 = new ExpressionElementMapperImpl();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      boolean boolean0 = true;
      expressionMatrixImpl0.creatMatrix(89);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getNumberOfElements();
      boolean boolean1 = true;
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getValue(364, 89);
      expressionMatrixImpl0.setValue(0, 0, 0);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.toString();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      ExpressionElementMapperImpl expressionElementMapperImpl1 = new ExpressionElementMapperImpl();
      ExpressionElementMapperItemImpl expressionElementMapperItemImpl0 = new ExpressionElementMapperItemImpl();
      expressionElementMapperImpl1.addItem(expressionElementMapperItemImpl0);
      // Undeclared exception!
      try { 
        expressionMatrixImpl0.outNoStandardConnections(true, expressionElementMapperImpl1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  /**
  //Test case number: 5
  /*Coverage entropy=1.8473007272027087
  */
  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.getValue(2, 2);
      expressionMatrixImpl0.setValue(2, 2, 1);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.toString();
      ExpressionMatrixImpl expressionMatrixImpl1 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.addNewNode();
      // Undeclared exception!
      expressionMatrixImpl0.toString();
  }

  /**
  //Test case number: 6
  /*Coverage entropy=1.8473007272027087
  */
  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.getValue(2, 3437);
      expressionMatrixImpl0.setValue(2, 2, 2176);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.toString();
      ExpressionMatrixImpl expressionMatrixImpl1 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.addNewNode();
      // Undeclared exception!
      expressionMatrixImpl0.toString();
  }

  /**
  //Test case number: 7
  /*Coverage entropy=2.157280995708096
  */
  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      HL7SegmentMapImpl hL7SegmentMapImpl0 = new HL7SegmentMapImpl();
      expressionMatrixImpl0.toString();
      hL7SegmentMapImpl0.getItem((String) null);
      HL7MessageSegmentImpl hL7MessageSegmentImpl0 = new HL7MessageSegmentImpl();
      hL7MessageSegmentImpl0.setSegment((HL7Segment) null);
      MessageTracerImpl messageTracerImpl1 = new MessageTracerImpl();
      messageTracerImpl0.reset();
      ExpressionImpl expressionImpl0 = new ExpressionImpl();
      messageTracerImpl1.doBeginItem(expressionImpl0, hL7MessageSegmentImpl0);
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      int int0 = 32768;
      expressionMatrixImpl0.creatMatrix(32768);
      expressionMatrixImpl0.getValue(330, 3665);
      // Undeclared exception!
      expressionMatrixImpl0.addNewNode();
  }

  /**
  //Test case number: 8
  /*Coverage entropy=1.830738805564335
  */
  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.creatMatrix((-646));
      int int0 = expressionMatrixImpl0.getNumberOfElements();
      assertEquals((-646), int0);
      
      expressionMatrixImpl0.getNumberOfNodes();
      assertEquals((-646), expressionMatrixImpl0.getNumberOfElements());
  }

  /**
  //Test case number: 9
  /*Coverage entropy=2.186294851794684
  */
  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.creatMatrix(89);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getValue(364, 89);
      expressionMatrixImpl0.setValue(0, (-35), 0);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      ExpressionElementMapperImpl expressionElementMapperImpl0 = new ExpressionElementMapperImpl();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      int int0 = expressionMatrixImpl0.getValue((-35), (-1));
      assertEquals(89, expressionMatrixImpl0.getNumberOfElements());
      assertEquals((-1), int0);
  }

  /**
  //Test case number: 10
  /*Coverage entropy=2.0365189803542108
  */
  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      ExpressionElementMapperImpl expressionElementMapperImpl0 = new ExpressionElementMapperImpl();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.creatMatrix(2357);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getValue(364, 2357);
      expressionMatrixImpl0.setValue(0, 1, 0);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      boolean boolean0 = false;
      // Undeclared exception!
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
  }

  /**
  //Test case number: 11
  /*Coverage entropy=2.329343492014154
  */
  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.addNewNode();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.creatMatrix(101);
      expressionMatrixImpl0.creatMatrix((-1879));
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.getValue(364, (-1879));
      expressionMatrixImpl0.setValue(1, 1, 1);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      assertEquals((-1879), expressionMatrixImpl0.getNumberOfElements());
  }

  /**
  //Test case number: 12
  /*Coverage entropy=1.8408398156653452
  */
  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl0 = new HL7MessageGroupImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl1 = new HL7MessageGroupImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl2 = new HL7MessageGroupImpl();
      hL7MessageGroupImpl0.addItem(hL7MessageGroupImpl1);
      hL7MessageGroupImpl2.setAdditional("org.apache.xpath.operations.Operation");
      hL7MessageGroupImpl0.getItem((-1698));
      hL7MessageGroupImpl0.addItem((HL7MessageGroupItem) null);
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl3 = new HL7MessageGroupImpl();
      hL7MessageGroupImpl1.setRepeatable(false);
      hL7MessageGroupImpl0.setItem((-1698), hL7MessageGroupImpl2);
      HL7MessageGroupImpl hL7MessageGroupImpl4 = new HL7MessageGroupImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl5 = new HL7MessageGroupImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl6 = new HL7MessageGroupImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl7 = new HL7MessageGroupImpl();
      hL7MessageGroupImpl5.setItem((-2052), hL7MessageGroupImpl3);
      MessageTracerImpl messageTracerImpl1 = new MessageTracerImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl8 = new HL7MessageGroupImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl9 = new HL7MessageGroupImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl10 = new HL7MessageGroupImpl();
      hL7MessageGroupImpl1.setItem((-1698), hL7MessageGroupImpl10);
      expressionMatrixImpl0.getValue((-2052), (-1698));
      expressionMatrixImpl0.setValue((-2052), 1060, 65);
      messageTracerImpl0.getMapper();
      ExpressionElementMapperImpl expressionElementMapperImpl0 = new ExpressionElementMapperImpl();
      expressionMatrixImpl0.outNoStandardConnections(false, expressionElementMapperImpl0);
      MessageTracerImpl messageTracerImpl2 = new MessageTracerImpl();
      messageTracerImpl2.getMapper();
      String string0 = expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      assertEquals("", string0);
  }

  /**
  //Test case number: 13
  /*Coverage entropy=2.12462407066152
  */
  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.creatMatrix(101);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.getValue(364, 101);
      expressionMatrixImpl0.setValue(0, 1, 0);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.addNewNode();
      int int0 = expressionMatrixImpl0.getValue(1, (-1));
      assertEquals(101, expressionMatrixImpl0.getNumberOfElements());
      assertEquals((-1), int0);
  }

  /**
  //Test case number: 14
  /*Coverage entropy=1.7842068034002128
  */
  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ExpressionElementMapperImpl expressionElementMapperImpl0 = new ExpressionElementMapperImpl();
      ExpressionElementMapperImpl expressionElementMapperImpl1 = new ExpressionElementMapperImpl();
      expressionElementMapperImpl1.removeItem(0);
      expressionElementMapperImpl1.removeItem(5484);
      expressionElementMapperImpl1.getItem(5484);
      expressionElementMapperImpl1.addItem((ExpressionElementMapperItem) null);
      expressionElementMapperImpl1.addItem((ExpressionElementMapperItem) null);
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.getValue(40, 1200);
      expressionMatrixImpl0.setValue(318, 0, 1748);
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, expressionElementMapperImpl0);
      messageTracerImpl0.getMapper();
      String string0 = expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      assertEquals("", string0);
  }

  /**
  //Test case number: 15
  /*Coverage entropy=1.0650855968662414
  */
  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.setValue(17, 17, 17);
      expressionMatrixImpl0.setValue(0, 6, 0);
      assertEquals(0, expressionMatrixImpl0.getNumberOfNodes());
  }

  /**
  //Test case number: 16
  /*Coverage entropy=2.1365318227137147
  */
  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.getValue(0, 3437);
      expressionMatrixImpl0.setValue(0, 0, 2176);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.toString();
      ExpressionMatrixImpl expressionMatrixImpl1 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.addNewNode();
      // Undeclared exception!
      expressionMatrixImpl0.toString();
  }

  /**
  //Test case number: 17
  /*Coverage entropy=2.1344989229646965
  */
  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      ExpressionElementMapperImpl expressionElementMapperImpl0 = new ExpressionElementMapperImpl();
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.creatMatrix(89);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getValue(364, 89);
      expressionMatrixImpl0.setValue(0, 1, 0);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      boolean boolean0 = false;
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      // Undeclared exception!
      try { 
        expressionMatrixImpl0.outNoStandardConnections(false, expressionElementMapperImpl0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  /**
  //Test case number: 18
  /*Coverage entropy=1.830738805564335
  */
  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.creatMatrix((-646));
      expressionMatrixImpl0.getNumberOfElements();
      // Undeclared exception!
      try { 
        expressionMatrixImpl0.addNewNode();
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.browsersoft.openhre.hl7.impl.regular.ExpressionMatrixImpl", e);
      }
  }

  /**
  //Test case number: 19
  /*Coverage entropy=1.7225422195731708
  */
  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.creatMatrix(78);
      expressionMatrixImpl0.creatMatrix(0);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.creatMatrix(1788);
      expressionMatrixImpl0.toString();
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.getNumberOfNodes();
      assertEquals(1788, expressionMatrixImpl0.getNumberOfElements());
  }

  /**
  //Test case number: 20
  /*Coverage entropy=1.7842068034002128
  */
  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.setValue(4, 4, 4);
      expressionMatrixImpl0.setValue(0, 0, 0);
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      int int0 = expressionMatrixImpl0.getValue(0, 72);
      assertEquals((-1), int0);
  }

  /**
  //Test case number: 21
  /*Coverage entropy=2.0057927995363096
  */
  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.getMapper();
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.creatMatrix(364);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.creatMatrix(101);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getNumberOfElements();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.getValue(364, 101);
      expressionMatrixImpl0.setValue(0, 1, 0);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      messageTracerImpl0.setMapper((ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      messageTracerImpl0.getMapper();
      expressionMatrixImpl0.outNoStandardConnections(false, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      expressionMatrixImpl0.outNoStandardConnections(true, (ExpressionElementMapper) null);
      ExpressionElementMapperImpl expressionElementMapperImpl0 = new ExpressionElementMapperImpl();
      // Undeclared exception!
      try { 
        expressionMatrixImpl0.outNoStandardConnections(true, expressionElementMapperImpl0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.System", e);
      }
  }

  /**
  //Test case number: 22
  /*Coverage entropy=1.7682293763712118
  */
  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      expressionMatrixImpl0.setValue(4, 4, 4);
      expressionMatrixImpl0.setValue(0, 0, 0);
      expressionMatrixImpl0.addNewNode();
      expressionMatrixImpl0.getValue(0, 342);
      int int0 = expressionMatrixImpl0.addNewNode();
      assertEquals(1, int0);
      
      expressionMatrixImpl0.creatMatrix(0);
      expressionMatrixImpl0.getValue((-1931), 99);
      int int1 = expressionMatrixImpl0.getValue(712, 341);
      assertEquals((-1), int1);
      assertEquals(0, expressionMatrixImpl0.getNumberOfElements());
  }

  /**
  //Test case number: 23
  /*Coverage entropy=1.0931471805599453
  */
  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ExpressionMatrixImpl expressionMatrixImpl0 = new ExpressionMatrixImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl0 = new HL7MessageGroupImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl1 = new HL7MessageGroupImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl2 = new HL7MessageGroupImpl();
      hL7MessageGroupImpl0.addItem(hL7MessageGroupImpl1);
      hL7MessageGroupImpl2.setAdditional("org.apache.xpath.operations.Operation");
      hL7MessageGroupImpl0.getItem((-1698));
      hL7MessageGroupImpl0.addItem((HL7MessageGroupItem) null);
      MessageTracerImpl messageTracerImpl0 = new MessageTracerImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl3 = new HL7MessageGroupImpl();
      hL7MessageGroupImpl2.setRequired(true);
      HL7MessageGroupImpl hL7MessageGroupImpl4 = new HL7MessageGroupImpl();
      hL7MessageGroupImpl4.setItem((-1698), (HL7MessageGroupItem) null);
      HL7MessageGroupImpl hL7MessageGroupImpl5 = new HL7MessageGroupImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl6 = new HL7MessageGroupImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl7 = new HL7MessageGroupImpl();
      hL7MessageGroupImpl7.setItem((-38), hL7MessageGroupImpl2);
      MessageTracerImpl messageTracerImpl1 = new MessageTracerImpl();
      HL7MessageGroupImpl hL7MessageGroupImpl8 = new HL7MessageGroupImpl();
      hL7MessageGroupImpl3.setItem((-38), hL7MessageGroupImpl4);
      HL7MessageGroupImpl hL7MessageGroupImpl9 = new HL7MessageGroupImpl();
      hL7MessageGroupImpl5.setAdditional("y)2R)2|#");
      HL7MessageGroupImpl hL7MessageGroupImpl10 = new HL7MessageGroupImpl();
      hL7MessageGroupImpl1.setItem(323, hL7MessageGroupImpl3);
      MessageTracerImpl messageTracerImpl2 = new MessageTracerImpl();
      int int0 = expressionMatrixImpl0.getNumberOfElements();
      assertEquals(0, int0);
  }
}
